GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/13

###

POST http://localhost:3000/subscribers
Content-Type: application/json
{
    "name": "John",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/13

###

PATCH http://localhost:3000/subscribers/13
Content-Type: application/json

{
    "name": "New Name"
}